fn circle = (pos, radius) => {
  const sg = startSketchOn('XY')
  |> startProfileAt([pos[0] + radius, pos[1]], %)
  |> arc({
       angle_end: 360,
       angle_start: 0,
       radius: radius
     }, %)
  |> close(%)
  return sg
}

const flangeBase = startSketchOn('XY')
  |> startProfileAt([8, 0], %)
  |> arc({
       angle_end: 360,
       angle_start: 0,
       radius: 8
     }, %)
  |> close(%)
  |> hole(circle([0, 0], 4), %)
  |> hole(circle([6.5, 0], .5), %)
  |> hole(circle([
       6.5 * cos(60 * pi() / 180),
       -6.5 * sin(60 * pi() / 180)
     ], .5), %)
  |> hole(circle([
       -6.5 * sin(30 * pi() / 180),
       -6.5 * cos(30 * pi() / 180)
     ], .5), %)
  |> hole(circle([-6.5, 0], .5), %)
  |> hole(circle([
       -6.5 * cos(60 * pi() / 180),
       6.5 * sin(60 * pi() / 180)
     ], .5), %)
  |> hole(circle([
       6.5 * sin(30 * pi() / 180),
       6.5 * cos(30 * pi() / 180)
     ], .5), %)
  |> extrude(3, %)

const flangePipe = startSketchOn(flangeBase, "end")
  |> startProfileAt([4.75, 0], %)
  |> arc({
       angle_end: 360,
       angle_start: 0,
       radius: 4.75
     }, %)
  |> close(%)
  |> hole(circle([0, 0], 4), %)
  |> extrude(5, %)
