const flangeBase = startSketchOn('XY')
  |> circle('XY',[0,0], 8)
  |> hole(circle('XY',[0, 0], 4), %)
  |> hole(circle('XY', [6.5, 0], .5), %)
  |> hole(circle('XY',[
       6.5 * cos(60 * pi() / 180),
       -6.5 * sin(60 * pi() / 180)
     ], .5), %)
  |> hole(circle('XY',[
       -6.5 * sin(30 * pi() / 180),
       -6.5 * cos(30 * pi() / 180)
     ], .5), %)
  |> hole(circle('XY',[-6.5, 0], .5), %)
  |> hole(circle('XY',[
       -6.5 * cos(60 * pi() / 180),
       6.5 * sin(60 * pi() / 180)
     ], .5), %)
  |> hole(circle('XY',[
       6.5 * sin(30 * pi() / 180),
       6.5 * cos(30 * pi() / 180)
     ], .5), %)
  |> extrude(3, %)

const flangePipe = startSketchOn(flangeBase, "end")
  |> startProfileAt([4.75, 0], %)
  |> arc({
       angle_end: 360,
       angle_start: 0,
       radius: 4.75
     }, %)
  |> close(%)
  |> hole(circle('XY',[0, 0], 4), %)
  |> extrude(5, %)